"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

# 项目所处的路径位置
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'bl$hldbi&+qu(&_g*q-jbleem@euh8vq_#42lv!4x&%m56-ror'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True     # 启用调试模式

ALLOWED_HOSTS = ["*"]    # 允许主机访问白名单


# Application definition
# 注册应用
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mainapp.apps.MainappConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

# templates 跟文件相关的配置
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # templates 的路径位置
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'stu_manage',
        'HOST': 'tzw160702.work',
        'PORT': '3307',
        'USER': 'root',
        'PASSWORD': 'password',
    }
}
# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True
USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/
# Django 具体APP下建立的static目录，用来存放静态资源
# 当一个以/static/开头的url请求过来时，Django会遍历所有的应用目录下面是否有/static目录以及读取目录下对应名字的文件返回给请求者。
STATIC_URL = '/static/'   # 别名，html中找静态文件（css/js/,image） 都要以这个别名开头

# Django项目中用到的静态文件的目录
# 通用的静态资源，对应项目根目录下的static
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    # print(os.path.join(BASE_DIR, "static"))
]


# # redis 配置
# CACHES = {
#   "default": {
#     "BACKEND": "django_redis.cache.RedisCache",
#     "LOCATION": "redis://59.110.235.115:6379/1",    # 使用 1 库存数据
#     "OPTIONS": {
#       "CLIENT_CLASS": "django_redis.client.DefaultClient",
#       "CONNECTION_POOL_KWARGS": {"max_connections": 100},
#       "PASSWORD": '123456',
#     }
#   }
# }
#
# # 本地缓存的方式
# SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
# # 用的是哪个缓存
# SESSION_CACHE_ALIAS = 'default'